global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 5s

  - job_name: 'nlp-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nlp-server:5001']
    scrape_interval: 5s 