spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:tcp://localhost/~/mixingbowl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 360000 # 1시간

app:
  frontend-url: http://localhost:5173

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.mixingbowl: DEBUG
    com.mixingbowl.filter: DEBUG
