version: '3.8'

services:
  nlp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=False
      - PORT=5001
    volumes:
      - ./nlp-server:/app