version: '3.8'

services:
  nlp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nlp-server:latest
    container_name: nlp-server
    restart: unless-stopped
    ports:
      - "${PORT:-5001}:${PORT:-5001}"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PORT=${PORT:-5001}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - .:/app
    networks:
      - nlp-network
    mem_limit: 1G
    cpus: 1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - nlp-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    depends_on:
      - prometheus
    networks:
      - nlp-network

networks:
  nlp-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: